# @baseUrl = https://rezeptor.azurewebsites.net
@baseUrl = http://localhost:7071
@sessionKey = 3ed292e765462ac233f6d726e8af67f4%3A863ff9c498f7cfc46c0e34f90e33b3dabf1e76a54a8c6cd11352aaea58248caa604e9af4e518c279f318301536398960

###

POST {{baseUrl}}/api/addCookbook
Cookie: session-key={{sessionKey}}
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="backCoverFile"; filename="example.jpg"
Content-Type: image/jpeg

< ./backcover1.jpg
--boundary--

###

GET {{baseUrl}}/api/getCookbook?id=2ec198a6-2dc9-4f6f-8f90-adb2c00eaa00
Cookie: session-key={{sessionKey}}

###

POST {{baseUrl}}/api/editCookbook
Cookie: session-key={{sessionKey}}
Content-Type: application/x-www-form-urlencoded

id=2ec198a6-2dc9-4f6f-8f90-adb2c00eaa00&title=Simple&authors=Yotam%20Ottolenghi

###

GET {{baseUrl}}/api/getCookbooks
Cookie: session-key={{sessionKey}}

###

POST {{baseUrl}}/api/addRecipe
Cookie: session-key={{sessionKey}}
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="cookbookId"

2ec198a6-2dc9-4f6f-8f90-adb2c00eaa00
--boundary
Content-Disposition: form-data; name="recipeFile"; filename="example.jpg"
Content-Type: image/jpeg

< ./recipe3.jpg
--boundary--

###

GET {{baseUrl}}/api/getRecipe?id=b1407271-1100-4713-b0bc-58419676eb65
Cookie: session-key={{sessionKey}}

###

GET {{baseUrl}}/api/getRecipes
Cookie: session-key={{sessionKey}}

###

POST {{baseUrl}}/api/editRecipe
Cookie: session-key={{sessionKey}}
Content-Type: application/x-www-form-urlencoded

id=b1407271-1100-4713-b0bc-58419676eb65&title=Involtini%20von%20Putenbrust%20und%20Fr%C3%BChlingskr%C3%A4utern%20mit%20Spinatsalat%20und%20ger%C3%B6steten%20Kartoffeln&pageNumber=238&cookbookId=2ec198a6-2dc9-4f6f-8f90-adb2c00eaa00

###

POST {{baseUrl}}/api/replaceRecipePhoto
Cookie: session-key={{sessionKey}}
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="id"

b1407271-1100-4713-b0bc-58419676eb65
--boundary
Content-Disposition: form-data; name="photoFile"; filename="example.jpg"
Content-Type: image/jpeg

< ./photo.jpg
--boundary--

###

GET {{baseUrl}}/api/getRecipePhoto?id=5bef21b9-5d05-42ad-8a9b-93592cd232bd
Cookie: session-key={{sessionKey}}

###

GET https://www.googleapis.com/books/v1/volumes?q=isbn:9783831046362
Cookie: session-key={{sessionKey}}