# @baseUrl = https://rezeptor.azurewebsites.net
@baseUrl = http://localhost:7071

###

POST {{baseUrl}}/api/addCookbook
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="backCoverFile"; filename="example.jpg"
Content-Type: image/jpeg

< ./backcover.jpg
--boundary--

###

GET {{baseUrl}}/api/getCookbook?id=4f357e2c-77ff-407d-97c1-6d5c1cb15cbc

###

POST {{baseUrl}}/api/editCookbook
Content-Type: application/x-www-form-urlencoded

id=4f357e2c-77ff-407d-97c1-6d5c1cb15cbc&title=Simple&authors=Yotam%20Ottolenghi

###

GET {{baseUrl}}/api/getCookbooks

###

POST {{baseUrl}}/api/addRecipe
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="cookbookId"

50de9498-4f93-4371-9082-0c4622d4e469
--boundary
Content-Disposition: form-data; name="recipeFile"; filename="example.jpg"
Content-Type: image/jpeg

< ./recipe4.jpg
--boundary--

###

GET {{baseUrl}}/api/getRecipe?id=1a469355-7211-42f6-8a48-314ffeabaffa

###

GET {{baseUrl}}/api/getRecipes

###

POST {{baseUrl}}/api/editRecipe
Content-Type: application/x-www-form-urlencoded

id=1a469355-7211-42f6-8a48-314ffeabaffa&title=Involtini%20von%20Putenbrust%20und%20Fr%C3%BChlingskr%C3%A4utern%20mit%20Spinatsalat%20und%20ger%C3%B6steten%20Kartoffeln&pageNumber=238

###

POST {{baseUrl}}/api/replaceRecipePhoto
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="id"

1a469355-7211-42f6-8a48-314ffeabaffa
--boundary
Content-Disposition: form-data; name="photoFile"; filename="example.jpg"
Content-Type: image/jpeg

< ./photo.jpg
--boundary--

###

GET {{baseUrl}}/api/getRecipePhoto?id=bf8515b0-8838-4a6f-85f6-0f7b6149dc79

###

GET https://www.googleapis.com/books/v1/volumes?q=isbn:9783831046362