apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  app: rezeptor

patches:
  - target:
      kind: Service
      name: app-name
    patch: |-
      - op: replace
        path: /metadata/name
        value: rezeptor
      - op: replace
        path: /spec/selector/app
        value: rezeptor
  - target:
      kind: Deployment
      name: app-name
    patch: |-
      - op: replace
        path: /metadata/name
        value: rezeptor
      - op: replace
        path: /spec/selector/matchLabels/app
        value: rezeptor
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: rezeptor
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/luchsamapparat/rezeptor:latest
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: rezeptor
  - target:
      kind: HorizontalPodAutoscaler
      name: app-name
    patch: |-
      - op: replace
        path: /metadata/name
        value: rezeptor
      - op: replace
        path: /spec/scaleTargetRef/name
        value: rezeptor
  - target:
      kind: PersistentVolumeClaim
      name: app-name
    patch: |-
      - op: replace
        path: /metadata/name
        value: rezeptor
