name: Build and deploy API

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Node ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        shell: pwsh
        run: |
          pushd ./api
          npm install
          npm run build
          npm prune --omit=dev
          popd

      - name: login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURESERVICEPRINCIPAL_CLIENTID }}","clientSecret":"${{ secrets.AZURESERVICEPRINCIPAL_CLIENTSECRET }}","subscriptionId":"${{ secrets.AZURESERVICEPRINCIPAL_SUBSCRIPTIONID }}","tenantId":"${{ secrets.AZURESERVICEPRINCIPAL_TENANTID }}"}'

      - name: deploy
        uses: Azure/functions-action@v1
        with:
          app-name: rezeptor
          slot-name: Production
          package: ./api
          respect-funcignore: true
          