name: Build and deploy API

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Node ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        shell: pwsh
        run: |
          pushd ./api
          npm install
          npm run build
          npm prune --omit=dev
          popd

      - name: zip artifact
        run: Compress-Archive -Path api/* -Destination api-release.zip

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-release
          path: api-release.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-release

      - name: unzip artifact
        run: Expand-Archive -Path api-release.zip -DestinationPath ./api
      
      - name: login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_862DA8CF642447A0AF58221280F0EBEB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C355C14F9E574A95BBA1AEDA831E98B1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E2494EA06DF477B8025635EF7EB0329 }}

      - name: deploy
        uses: Azure/functions-action@v1
        with:
          app-name: rezeptor
          slot-name: Production
          package: ./api
          respect-funcignore: true
          