name: Build and deploy App

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/app.yml'
      - 'app/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  VITE_API_BASE_URL: 'https://api.rezeptor.luchsamappar.at/api'
  VITE_APPLICATION_INSIGHTS_CONNECTION_STRING: 'InstrumentationKey=ab40e922-e66a-434f-a78d-66ec6ee8f20a;IngestionEndpoint=https://germanywestcentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://germanywestcentral.livediagnostics.monitor.azure.com'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Node ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        run: |
          pushd ./app
          npm ci
          npm run build
          cp ./staticwebapp.config.json ./dist/client/
          popd

      - name: zip artifact
        run: zip app-release.zip ./app/dist/client/* -r

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: unzip artifact
        run: unzip app-release.zip

      - name: debug
        shell: bash
        run: |
          ls -R

      - name: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURESTATICWEBAPPS_APITOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ./app/dist/client
          output_location: .
          skip_app_build: true